### ISSUE TITLE
Please upgrade Spatie/DTO..

### ISSUE THREAD

**Issue by peterabarry** [carboneio/carbone-sdk-php#1]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/963982/219367982-25749a64-958b-4364-a702-24b750a94c01.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/963982/219368075-c51ebf5c-4aed-4e4b-b124-dc76f74b6a8a.png">

**Comment by steevepay** [comment]
Fixed, spati/dto is removed from the SDK, update the package to the 1.0.1
https://packagist.org/packages/carboneio/carbone-sdk-php
