### ISSUE TITLE
Update your dependencies, add dependabot etc [laravel 11 upgrade blocker]

### ISSUE THREAD

**Issue by peterabarry** [carboneio/carbone-sdk-php#5]
"saloonphp/saloon" is now two major versions behind? 
Cannot upgrade due to illuminate/support conflict with laravel core.

**Comment by steevepay** [comment]
We just upgraded the Carbone SDK to PHP 8.2 and the latest version of Saloon.
Github release: https://github.com/carboneio/carbone-sdk-php/releases
Packagist release: https://packagist.org/packages/carboneio/carbone-sdk-php
